version: "3.9"
services:
    backend:
        build: Backend/
        container_name: backend
        ports:
            - 5000:5000
        networks:
            blocknet:
    mock:
        build: MockBlockchainService/
        container_name: mockblockchainservice
        ports:
            - 5001:5001
        networks:
            blocknet:
    db:
        build: db/
        container_name: db
        ports:
            - 5432:5432
        networks:
            blocknet:
networks:
    blocknet:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.0.0.0/16
                  gateway: 172.0.0.1